CREATE TABLE IF NOT EXISTS "lacrimeanalysis" (
    id serial primary key,
    _c0 int,
    dr_no varchar(10),
    date_rptd date,
    date_occ date,
    time_occ varchar(50),
    area varchar(10),
    area_name varchar(255),
    rpt_dist_no varchar(30),
    part_1_2 int,
    crm_cd int,
    crm_cd_desc varchar(255),
    mocodes varchar(255),
    vict_age int,
    vict_sex varchar(10),
    vict_descent varchar(20),
    premis_cd varchar(255),
    premis_desc varchar(255),
    "status" varchar(255),
    status_desc varchar(255),
    crm_cd_1 varchar(255),
    crm_cd_2 varchar(255),
    crm_cd_3 varchar(255),
    crm_cd_4 varchar(255),
    lat float,
    lon float,
    weapon_used_cd varchar(255),
    weapon_desc varchar(255),
    cross_street varchar(255),
    "location" varchar(255)
);